### ISSUE TITLE
Implement #g (go to line)

### ISSUE THREAD

**Issue by BlueDrink9** [idvorkin/Vim-Keybindings-For-Onenote#18]
Will rely on a method to get the current line number. Can be relatively moved from there.

**Comment by BlueDrink9** [comment]
Relies on #12

**Comment by idvorkin** [comment]
I tried out up and down after your changes.   It's pretty slow

**Comment by BlueDrink9** [comment]
#10 
Yup. I might add an option to change up and down. Slow but accurate vs fast and inaccurate. It's slowest at the start of the line, because it has to wait for the clipboard copy to time out. I'll shorten the timeout. Should be fine.
I must apologise, I've been a whirlwind of implementation and haven't done much robust testing, but I'll be focusing on that now, seeing as all the easy stuff is in.
