### ISSUE TITLE
Add option for slow/fast scroll behavior.

### ISSUE THREAD

**Issue by idvorkin** [idvorkin/Vim-Keybindings-For-Onenote#36]
The new implementation is really sluggish, add an option to pick between "fast and feature poor" and "slow and feature rich"

**Comment by idvorkin** [comment]
Hey @BlueDrink9 for my learning I setup up a [waffle.io](https://waffle.io/idvorkin/Vim-Keybindings-For-Onenote?utm_source=badge), and we also have a [gitter](https://gitter.im/idvorkin/Vim-Keybindings-For-Onenote) feel free to give them a try.

**Comment by BlueDrink9** [comment]
Thank you! By scroll, are you referring to j/k? There's already an issue for that option.
But yeah, I've been considering having a switch for exactly those options.

**Comment by BlueDrink9** [comment]
Also I made a pre-release from the last version you worked on, so at least there's that (before I started messing with things)

**Comment by BlueDrink9** [comment]
If you were referring to j/k, that is no longer an issue (which I'm so stoked about)

**Comment by idvorkin** [comment]
Agreed - much better speed now.
