### ISSUE TITLE
w and e no longer work

### ISSUE THREAD

**Issue by idvorkin** [idvorkin/Vim-Keybindings-For-Onenote#37]
w and e are not. I can see 'w' moving forward, and then jumping back, e doesn't do anything.  FYI, b still works. 

I'm on: 
67a98a6dc55ef9c61356e5cb1505a3663ab82c10

**Comment by BlueDrink9** [comment]
Thanks, I'll fix that asap

**Comment by BlueDrink9** [comment]
Darn, I tried that commit's version on my machine and w and e work fine. Is that from a fresh restart of a script?

**Comment by BlueDrink9** [comment]
I think you had probably pressed v, to enter visual. I've opened a separate issue for that. #39

**Comment by idvorkin** [comment]
I can no longer repro, closing.
