### ISSUE TITLE
w does not work

### ISSUE THREAD

**Issue by idvorkin** [idvorkin/Vim-Keybindings-For-Onenote#40]
*Hymn, thought I already created this issue, but recreating as I can't find it* 

Repro's on: f68d842097f68e214efb2e0e8d165a1247003bbc

When hitting w, the cursor jumps forward and then back.

See example: http://i.imgur.com/XU8Erok.gifv

**Comment by idvorkin** [comment]
The binary was stale - checking in rebuilt version @ eb766d99384a036f8e9296057725197b0c1b7a42

**Comment by BlueDrink9** [comment]
I've been having a problem with keeping the binary up to date. When the majority of the current bugs are fixed and there are basic test cases for the features, I'll consider making a release.
Otherwise, any ideas for keeping it up to date?

**Comment by idvorkin** [comment]
*I've never done this on github, but in broad strokes* 

This should be part of a continuos integration (CI) system.  For every checkin: 

1) Test get run.  On success: 
2) Binary gets built and checkin 

Ideally,  this gets done using a managed system so you don't need to manage your own build virtual machines.

Should be a fun task, feel free to create an issue for it.
