### ISSUE TITLE
Does not support OneNote UWP

### ISSUE THREAD

**Issue by Explorare** [idvorkin/Vim-Keybindings-For-Onenote#46]
It seems that this plugin doesn't support OneNote UWP?

**Comment by BlueDrink9** [comment]
UWP?

There hasn't been a lot of work on this plugin in a while, but consider using rcmdnk/vim_ahk as a temporary workaround.

This is probably not working because the window title is not as expected. Knowing what that title is would help a lot.

**Comment by Explorare** [comment]
Thanks for your reply. The window title is "OneNote".
