### ISSUE TITLE
Implement c

### ISSUE THREAD

**Issue by BlueDrink9** [idvorkin/Vim-Keybindings-For-Onenote#8]
Eg cw should delete word and switch off active mode.

**Comment by idvorkin** [comment]
Hey @BlueDrink9  I haven't been using this plugin for a while.  Are you interested in working on some of these features?

**Comment by BlueDrink9** [comment]
Yeah, I will be sorting most of these issues after my finals. Just putting them all here as I think of them, and putting notes.
Feel free to give me push access if you don't want to deal with pull requests, or wait till I have something.

**Comment by idvorkin** [comment]
Looking forward to it! If you add enough functionality, I might start using
OneNote more heavily.

**Comment by BlueDrink9** [comment]
Haha well that's the goal. I'm a massive user of both Onenote and Autohotkey, and just recently learned and fell in love with vim. Never could get the hang of Emacs keybindings. So yeah, this project excites me

**Comment by idvorkin** [comment]
BTW - You might be interested in my other OneNote project - https://github.com/idvorkin/onom .  It helps you if want to automate via the C# interface, and includes a sample app which lets you use daily and weekly templates.

**Comment by BlueDrink9** [comment]
This issue is resolved by https://github.com/BlueDrink9/Vim-Keybindings-For-Onenote/commit/d4b2e4cd41d39f7f21e9e534a9d9bed9b93b81c6
